import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-sky-600 via-sky-400 to-sky-600 text-white">
        {children}
      </body>
    </html>
  );
}
